version: '3.8'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    privileged: true
    restart: unless-stopped
    user: root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins-ssl.entrypoints=https"
      - "traefik.http.routers.jenkins-ssl.rule=Host(`FQDN`)"
      - "traefik.http.routers.jenkins-ssl.middlewares=default@file"
      - "traefik.http.routers.jenkins-ssl.tls=true"
      - "traefik.http.routers.jenkins-ssl.tls.certresolver=http"
      - "traefik.http.routers.jenkins-ssl.service=jenkins-ssl"
      - "traefik.http.services.jenkins-ssl.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

    networks:
      - proxy
      - default
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /opt/containers/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true
