pipeline {

    agent { label "${ENV_AGENT}" }


   parameters {
       choice(name: 'ENV_AGENT', choices: ['DEV', 'STAG', 'PROD'], description: 'The environment agent to deploy to ${ENV_AGENT}')
    }


   stages {

   steps {
        script {
            def cmd = "mein befehl"
            def proc = cmd.execute()
            proc.waitForProcessOutput(System.out, System.err)
        }
    }
}

        stage('Check running docker container') {
            steps {
                sh '''docker ps > ausgabe.txt'''
                archiveArtifacts artifacts: 'ausgabe.txt', onlyIfSuccessful: true
            }
		}   
    }
}
