version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    environment: 
      POSTGRES_USER: DBUSER
      POSTGRES_PASSWORD: PASSWORDS
      POSTGRES_DB: DB

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: DBUSER
      DB_PASSWORD: PASSWORDS
      DB_HOST: 'postgres'
 #    # BASE_URL: "http://localhost:5000"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.peppermin-ssl.entrypoints=https"
      - "traefik.http.routers.peppermin-ssl.rule=Host(`FQDN`)"
      - "traefik.http.routers.peppermin-ssl.middlewares=default@file"
      - "traefik.http.routers.peppermin-ssl.tls=true"
      - "traefik.http.routers.peppermin-ssl.tls.certresolver=http"
      - "traefik.http.routers.peppermin-ssl.service=peppermin-ssl"
      - "traefik.http.services.peppermin-ssl.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default
      
networks:
  proxy:
    external: true 
